spring.application.name=api-gateway
server.port=8080

spring.http.client.redirects=follow_when_possible

eureka.client.service-url.defaultZone=http://localhost:8090/eureka
eureka.client.registry-fetch-interval-seconds=5
eureka.client.initial-instance-info-replication-interval-seconds=5

jwt.secret=2B-PIT)bgCc.0Z|O?N}wbH~EPjQZ)jiV

spring.cloud.gateway.mvc.routes[0].id=catalogo-route
spring.cloud.gateway.mvc.routes[0].uri=lb://CATALOGO
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/instrumentos,/instrumentos/**

spring.cloud.gateway.mvc.routes[1].id=inventario-route
spring.cloud.gateway.mvc.routes[1].uri=lb://INVENTARIO
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/inventario,/inventario/**

spring.cloud.gateway.mvc.routes[2].id=compra-route
spring.cloud.gateway.mvc.routes[2].uri=lb://COMPRA
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/compras,/compras/**

spring.cloud.gateway.mvc.routes[3].id=pago-route
spring.cloud.gateway.mvc.routes[3].uri=lb://PAGO
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/pagos,/pagos/**

spring.cloud.gateway.mvc.routes[4].id=reserva-route
spring.cloud.gateway.mvc.routes[4].uri=lb://RESERVA
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/reservas,/reservas/**

spring.cloud.gateway.mvc.routes[5].id=postventa-route
spring.cloud.gateway.mvc.routes[5].uri=lb://POSTVENTA
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/postventa,/postventa/**

spring.cloud.gateway.mvc.routes[6].id=despacho-route
spring.cloud.gateway.mvc.routes[6].uri=lb://DESPACHO
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/despachos,/despachos/**

spring.cloud.gateway.mvc.routes[7].id=usuario-route
spring.cloud.gateway.mvc.routes[7].uri=lb://USUARIO
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/usuarios,/usuarios/**

spring.cloud.gateway.mvc.routes[8].id=cotizaciones-route
spring.cloud.gateway.mvc.routes[8].uri=lb://COTIZACIONES
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/cotizaciones,/cotizaciones/**

spring.cloud.gateway.mvc.routes[9].id=resenas-route
spring.cloud.gateway.mvc.routes[9].uri=lb://RESENAS
spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/resenas,/resenas/**

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
