spring.application.name=USUARIO

server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8090/eureka
jwt.secret=2B-PIT)bgCc.0Z|O?N}wbH~EPjQZ)jiV

spring.datasource.url=jdbc:mysql://localhost:3306/usuario_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
